#
# BitHawk recipes YAML Configuration File
#
# Contains Recipes (build descriptions) for projects hosted on remote VCS services (github, bitbucket)
#

# THIS IS AN EXAMPLE RECIPE
myapp-dev:
  repository:
    name: myapp
    branch: dev
    url: "git@bitbucket.org:stek.io/website.git"
    vcs: git
  command: "python ./bin/fabfile.py -f -s -a build"

simple-build:
  command: "pwd && ls -la"